"""Patch notebook 10: fix Open Meteo SSL, add chunked fetch, update solar comparison."""
import json

NB = "notebooks/analysis/10_cooling_thermal_calibration.ipynb"
with open(NB, "r", encoding="utf-8") as f:
    nb = json.load(f)

# ---- Cell 20 (id=05ee03ec): Open Meteo fetch with SSL bypass + monthly chunking ----
FETCH_CELL = [
    "import requests, urllib3, calendar\n",
    "from datetime import datetime, timedelta\n",
    "\n",
    "# Suppress SSL warnings (corporate proxy intercepts TLS)\n",
    "urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)\n",
    "\n",
    "LAT = 48.928\n",
    "LON = 10.069\n",
    "\n",
    "doy_angle = np.arctan2(df_clean['doy_sin'], df_clean['doy_cos'])\n",
    "doy = (doy_angle * 365.25 / (2 * np.pi)) % 365.25\n",
    "doy_min, doy_max = int(doy.min()), int(doy.max())\n",
    "print(f'DOY range in data: {doy_min} to {doy_max}')\n",
    "print(f'Location: {LAT}N, {LON}E')\n",
    "\n",
    "HOURLY_VARS = 'shortwave_radiation,direct_radiation,diffuse_radiation,direct_normal_irradiance'\n",
    "\n",
    "def fetch_open_meteo_chunk(start_date, end_date):\n",
    "    url = (\n",
    "        f'https://archive-api.open-meteo.com/v1/archive?'\n",
    "        f'latitude={LAT}&longitude={LON}'\n",
    "        f'&start_date={start_date}&end_date={end_date}'\n",
    "        f'&hourly={HOURLY_VARS}'\n",
    "        f'&timezone=Europe%2FBerlin'\n",
    "    )\n",
    "    resp = requests.get(url, timeout=60, verify=False)\n",
    "    resp.raise_for_status()\n",
    "    data = resp.json()\n",
    "    if 'error' in data:\n",
    "        raise ValueError(data.get('reason', data['error']))\n",
    "    return data\n",
    "\n",
    "# Fetch monthly chunks: May 2025 - May 2026\n",
    "chunks = []\n",
    "solar_df = None\n",
    "fetch_errors = []\n",
    "\n",
    "print('\\nFetching Open Meteo archive (verify=False for corporate proxy)...')\n",
    "\n",
    "month_starts = []\n",
    "y, m = 2025, 5\n",
    "while (y, m) <= (2026, 5):\n",
    "    month_starts.append((y, m))\n",
    "    m += 1\n",
    "    if m > 12:\n",
    "        m = 1\n",
    "        y += 1\n",
    "\n",
    "for y, m in month_starts:\n",
    "    last_day = calendar.monthrange(y, m)[1]\n",
    "    s_str = f'{y}-{m:02d}-01'\n",
    "    e_str = f'{y}-{m:02d}-{last_day:02d}'\n",
    "    try:\n",
    "        data = fetch_open_meteo_chunk(s_str, e_str)\n",
    "        hourly = data['hourly']\n",
    "        chunk_df = pd.DataFrame({\n",
    "            'timestamp': pd.to_datetime(hourly['time']),\n",
    "            'ghi_wm2': hourly['shortwave_radiation'],\n",
    "            'direct_wm2': hourly['direct_radiation'],\n",
    "            'diffuse_wm2': hourly['diffuse_radiation'],\n",
    "            'dni_wm2': hourly['direct_normal_irradiance'],\n",
    "        })\n",
    "        chunks.append(chunk_df)\n",
    "        print(f'  {s_str} to {e_str}: {len(chunk_df)} hours OK')\n",
    "    except Exception as e:\n",
    "        err_msg = str(e)[:100]\n",
    "        fetch_errors.append((s_str, err_msg))\n",
    "        print(f'  {s_str} to {e_str}: FAILED ({err_msg})')\n",
    "\n",
    "if chunks:\n",
    "    solar_df = pd.concat(chunks, ignore_index=True)\n",
    "    solar_df = solar_df.set_index('timestamp').sort_index()\n",
    "    solar_df = solar_df[~solar_df.index.duplicated(keep='first')]\n",
    "    print(f'\\nTotal: {len(solar_df)} hourly records')\n",
    "    print(f'Date range: {solar_df.index.min()} to {solar_df.index.max()}')\n",
    "    print(f'GHI: mean={solar_df[\"ghi_wm2\"].mean():.1f}, max={solar_df[\"ghi_wm2\"].max():.1f} W/m2')\n",
    "    print(f'DNI: mean={solar_df[\"dni_wm2\"].mean():.1f}, max={solar_df[\"dni_wm2\"].max():.1f} W/m2')\n",
    "    if fetch_errors:\n",
    "        print(f'\\n{len(fetch_errors)} chunks failed (likely future dates not in archive)')\n",
    "else:\n",
    "    print('\\nArchive API failed. Trying forecast API (past_days=92)...')\n",
    "    try:\n",
    "        url = (\n",
    "            f'https://api.open-meteo.com/v1/forecast?'\n",
    "            f'latitude={LAT}&longitude={LON}'\n",
    "            f'&hourly={HOURLY_VARS}'\n",
    "            f'&past_days=92&forecast_days=0'\n",
    "            f'&timezone=Europe%2FBerlin'\n",
    "        )\n",
    "        resp = requests.get(url, timeout=60, verify=False)\n",
    "        resp.raise_for_status()\n",
    "        data = resp.json()\n",
    "        hourly = data['hourly']\n",
    "        solar_df = pd.DataFrame({\n",
    "            'timestamp': pd.to_datetime(hourly['time']),\n",
    "            'ghi_wm2': hourly['shortwave_radiation'],\n",
    "            'direct_wm2': hourly['direct_radiation'],\n",
    "            'diffuse_wm2': hourly['diffuse_radiation'],\n",
    "            'dni_wm2': hourly['direct_normal_irradiance'],\n",
    "        }).set_index('timestamp')\n",
    "        print(f'Forecast API fallback: {len(solar_df)} hours')\n",
    "        print(f'Date range: {solar_df.index.min()} to {solar_df.index.max()}')\n",
    "    except Exception as e2:\n",
    "        print(f'Forecast API also failed: {e2}')\n",
    "        solar_df = None\n",
    "\n",
    "if solar_df is not None:\n",
    "    display(solar_df.describe().round(1))\n",
]

# ---- Cell 22 (id=bc401fd0): Replace PV-only proxy with dual-source comparison ----
COMPARISON_CELL = [
    "# Solar radiation analysis: Open Meteo data + PV comparison\n",
    "\n",
    "has_solar = (solar_df is not None\n",
    "             and 'ghi_wm2' in df_merged.columns\n",
    "             and df_merged['ghi_wm2'].notna().sum() > 100)\n",
    "\n",
    "fig, axes = plt.subplots(2, 3, figsize=(18, 10))\n",
    "cooling_active = df_clean[df_clean['is_cooling_active']].copy()\n",
    "\n",
    "# 1) PV vs indoor temp change\n",
    "ax = axes[0, 0]\n",
    "ax.scatter(cooling_active['PV_Generate'], cooling_active['indoor_trend_30m'],\n",
    "           alpha=0.2, s=5, c='steelblue')\n",
    "ax.set_xlabel('PV Generate (W)')\n",
    "ax.set_ylabel('Indoor Trend 30min (C)')\n",
    "ax.set_title('Solar (PV) vs Indoor Temp Change')\n",
    "ax.axhline(0, color='red', ls='--', alpha=0.5)\n",
    "corr_pv_trend = cooling_active['PV_Generate'].corr(cooling_active['indoor_trend_30m'])\n",
    "ax.text(0.05, 0.95, f'r = {corr_pv_trend:.3f}', transform=ax.transAxes, fontsize=12, va='top')\n",
    "\n",
    "# 2) GHI vs PV (or PV vs cooling power if no solar)\n",
    "ax = axes[0, 1]\n",
    "if has_solar:\n",
    "    mc = df_merged[df_merged['is_cooling_active'] & df_merged['ghi_wm2'].notna()]\n",
    "    ax.scatter(mc['ghi_wm2'], mc['PV_Generate'], alpha=0.2, s=5, c='coral')\n",
    "    r_ghi_pv = mc['ghi_wm2'].corr(mc['PV_Generate'])\n",
    "    ax.set_xlabel('GHI (W/m2, Open Meteo)')\n",
    "    ax.set_ylabel('PV Generate (W)')\n",
    "    ax.set_title(f'GHI vs PV (r={r_ghi_pv:.3f})')\n",
    "    ax.text(0.05, 0.95, f'r = {r_ghi_pv:.3f}', transform=ax.transAxes, fontsize=12, va='top')\n",
    "else:\n",
    "    ax.scatter(cooling_active['PV_Generate'], cooling_active['thermal_power_kw'],\n",
    "               alpha=0.2, s=5, c='coral')\n",
    "    corr2 = cooling_active['PV_Generate'].corr(cooling_active['thermal_power_kw'])\n",
    "    ax.set_xlabel('PV Generate (W)')\n",
    "    ax.set_ylabel('Thermal Power (kW)')\n",
    "    ax.set_title(f'PV vs Cooling Power (r={corr2:.3f})')\n",
    "\n",
    "# 3) Diurnal cycle comparison\n",
    "ax = axes[0, 2]\n",
    "hourly_pv = df_clean.groupby('hour')['PV_Generate'].mean()\n",
    "ax.bar(hourly_pv.index, hourly_pv.values, alpha=0.3, color='gold', label='PV (W)')\n",
    "ax2_twin = ax.twinx()\n",
    "if has_solar:\n",
    "    hourly_ghi = df_merged.groupby('hour_approx')['ghi_wm2'].mean().dropna()\n",
    "    ax2_twin.plot(hourly_ghi.index, hourly_ghi.values, 'r-o', ms=4, label='GHI (W/m2)')\n",
    "    ax2_twin.set_ylabel('GHI (W/m2)', color='red')\n",
    "else:\n",
    "    hourly_cool = cooling_active.groupby('hour')['thermal_power_kw'].mean()\n",
    "    ax2_twin.plot(hourly_cool.index, hourly_cool.values, 'r-o', ms=4, label='Cool power (kW)')\n",
    "    ax2_twin.set_ylabel('Cooling Power (kW)', color='red')\n",
    "ax.set_xlabel('Hour of Day')\n",
    "ax.set_ylabel('PV Generate (W)', color='goldenrod')\n",
    "ax.set_title('Diurnal: Solar Sources')\n",
    "ax.legend(loc='upper left', fontsize=9)\n",
    "ax2_twin.legend(loc='upper right', fontsize=9)\n",
    "\n",
    "# 4) GHI vs indoor trend (or OE by PV band)\n",
    "ax = axes[1, 0]\n",
    "if has_solar:\n",
    "    mc2 = df_merged[df_merged['is_cooling_active'] & df_merged['ghi_wm2'].notna()]\n",
    "    ax.scatter(mc2['ghi_wm2'], mc2['indoor_trend_30m'], alpha=0.2, s=5, c='teal')\n",
    "    r_ghi_trend = mc2['ghi_wm2'].corr(mc2['indoor_trend_30m'])\n",
    "    ax.set_xlabel('GHI (W/m2)')\n",
    "    ax.set_ylabel('Indoor Trend 30min (C)')\n",
    "    ax.set_title(f'GHI vs Indoor Change (r={r_ghi_trend:.3f})')\n",
    "    ax.axhline(0, color='red', ls='--', alpha=0.5)\n",
    "    ax.text(0.05, 0.95, f'r = {r_ghi_trend:.3f}', transform=ax.transAxes, fontsize=12, va='top')\n",
    "else:\n",
    "    if 'oe_raw' in df_clean.columns:\n",
    "        oe_data = df_clean[df_clean['is_cooling_active'] & df_clean['oe_raw'].between(0, 3)].copy()\n",
    "        oe_data['pv_band'] = pd.cut(oe_data['PV_Generate'],\n",
    "                                     bins=[0, 100, 2000, 5000, 15000],\n",
    "                                     labels=['Night\\n<100W', 'Low\\n100-2kW', 'Med\\n2-5kW', 'High\\n>5kW'])\n",
    "        oe_by_band = oe_data.groupby('pv_band')['oe_raw'].agg(['median', 'mean', 'count'])\n",
    "        bars = ax.bar(range(len(oe_by_band)), oe_by_band['median'], alpha=0.8,\n",
    "                      color=['navy', 'steelblue', 'gold', 'orangered'], edgecolor='black')\n",
    "        ax.set_xticks(range(len(oe_by_band)))\n",
    "        ax.set_xticklabels(oe_by_band.index)\n",
    "        ax.set_ylabel('OE (median)')\n",
    "        ax.set_title('OE by Solar Intensity Band')\n",
    "\n",
    "# 5) DNI vs PV (or HLC by solar band)\n",
    "ax = axes[1, 1]\n",
    "if has_solar and 'dni_wm2' in df_merged.columns:\n",
    "    mc3 = df_merged[df_merged['is_cooling_active'] & df_merged['dni_wm2'].notna()]\n",
    "    ax.scatter(mc3['dni_wm2'], mc3['PV_Generate'], alpha=0.2, s=5, c='orange')\n",
    "    r_dni_pv = mc3['dni_wm2'].corr(mc3['PV_Generate'])\n",
    "    ax.set_xlabel('DNI (W/m2, Open Meteo)')\n",
    "    ax.set_ylabel('PV Generate (W)')\n",
    "    ax.set_title(f'DNI vs PV (r={r_dni_pv:.3f})')\n",
    "    ax.text(0.05, 0.95, f'r = {r_dni_pv:.3f}', transform=ax.transAxes, fontsize=12, va='top')\n",
    "else:\n",
    "    pv_bands = [(0, 100, 'Night (<100W)'), (100, 2000, 'Low (100-2kW)'),\n",
    "                (2000, 5000, 'Med (2-5kW)'), (5000, 15000, 'High (>5kW)')]\n",
    "    band_hlcs = []\n",
    "    for lo, hi, name in pv_bands:\n",
    "        mask = (df_clean['is_cooling_active']) & (df_clean['PV_Generate'] >= lo) & (df_clean['PV_Generate'] < hi)\n",
    "        subset = df_clean[mask]\n",
    "        if len(subset) > 20:\n",
    "            x = subset['driving_force'].values\n",
    "            y = subset['thermal_power_kw'].values\n",
    "            coeffs = np.polyfit(x, y, 1)\n",
    "            band_hlcs.append((name, coeffs[0], len(subset)))\n",
    "    if band_hlcs:\n",
    "        names_b, hlcs_b, counts_b = zip(*band_hlcs)\n",
    "        colors_band = ['navy', 'steelblue', 'gold', 'orangered'][:len(names_b)]\n",
    "        ax.bar(range(len(names_b)), hlcs_b, color=colors_band, alpha=0.8, edgecolor='black')\n",
    "        ax.set_xticks(range(len(names_b)))\n",
    "        ax.set_xticklabels(names_b, fontsize=9)\n",
    "        ax.set_ylabel('HLC (OLS slope)')\n",
    "        ax.set_title('HLC by Solar Band')\n",
    "\n",
    "# 6) Summary\n",
    "ax = axes[1, 2]\n",
    "ax.axis('off')\n",
    "lines = ['Solar Radiation Analysis', '=' * 35, '']\n",
    "lines.append(f'PV vs indoor_trend: r = {corr_pv_trend:.3f}')\n",
    "if has_solar:\n",
    "    lines.append(f'GHI vs PV: r = {r_ghi_pv:.3f}')\n",
    "    lines.append(f'GHI vs indoor_trend: r = {r_ghi_trend:.3f}')\n",
    "    lines.append(f'DNI vs PV: r = {r_dni_pv:.3f}')\n",
    "    lines.append('')\n",
    "    lines.append('Open Meteo data available!')\n",
    "else:\n",
    "    lines.append('')\n",
    "    lines.append('Open Meteo: NOT available')\n",
    "    lines.append('Using PV_Generate as proxy')\n",
    "lines.extend(['', 'Recommendation:', '  Compare GHI/DNI/direct/diffuse',\n",
    "              '  against PV for thermal model'])\n",
    "ax.text(0.05, 0.95, '\\n'.join(lines), transform=ax.transAxes, fontsize=11,\n",
    "        verticalalignment='top', fontfamily='monospace',\n",
    "        bbox=dict(boxstyle='round', facecolor='lightyellow', alpha=0.8))\n",
    "\n",
    "source_lbl = 'Open Meteo + PV' if has_solar else 'PV Proxy'\n",
    "plt.suptitle(f'Phase E: Solar Radiation Analysis ({source_lbl})', fontsize=14, fontweight='bold')\n",
    "plt.tight_layout()\n",
    "plt.show()\n",
]

# ---- Apply patches ----
# Cell 20: Open Meteo fetch
nb["cells"][20]["source"] = FETCH_CELL
nb["cells"][20]["execution_count"] = None
nb["cells"][20]["outputs"] = []

# Cell 22: Comparison (was PV-only proxy)
nb["cells"][22]["source"] = COMPARISON_CELL
nb["cells"][22]["execution_count"] = None
nb["cells"][22]["outputs"] = []

# Clear outputs of downstream cells (21, 24, 25, 27) so they re-run cleanly
for idx in [21, 24, 25, 27]:
    nb["cells"][idx]["execution_count"] = None
    nb["cells"][idx]["outputs"] = []

with open(NB, "w", encoding="utf-8") as f:
    json.dump(nb, f, ensure_ascii=False, indent=1)

print("Notebook patched successfully!")
print(f"  Cell 20 (fetch): {len(FETCH_CELL)} lines")
print(f"  Cell 22 (comparison): {len(COMPARISON_CELL)} lines")
print("  Cleared outputs on cells 21, 24, 25, 27")
